version: '3'
services:
  ros:
    image: ros-desktop
    platform: linux/amd64
    container_name: hiwin_dev
    # 添加 user: root 設置
    user: root
    # 將外部的 ROSdev 卷掛載到容器的 /home/ROS/workspace 目錄
    volumes:
      - hiwin_dev:/home/ROS/workspace 
    ports:
      - "5904:5901"
      - "8083:8080"
    # 添加重啟策略
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=ros000
    # 确保容器不会自动退出
    tty: true
    stdin_open: true

volumes:
  hiwin_dev:
    external: true