version: '3'
services:
  ros:
    image: ros-desktop
    platform: linux/amd64
    container_name: ROStest
    # 添加 user: root 設置
    user: root
    # 將外部的 ROSdev 卷掛載到容器的 /home/ROS/workspace 目錄
    volumes:
      - ROStest:/home/ROS/workspace 
    ports:
      - "5903:5901"
      - "8082:8080"
    # 添加重啟策略
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=ros000
    # 确保容器不会自动退出
    tty: true
    stdin_open: true

volumes:
  ROStest:
    external: true