version: '3'
services:
  ros:
    image: ros-desktop
    container_name: ROStest
    user: root
    volumes:
      - ROStest:/home/ROS/workspace 
    # ----------------------------------------------------------------
    # 1) 讓容器可以解析到宿主機（macOS/Docker Desktop/OrbStack）
    #    host.docker.internal 這個 DNS 會自動指向您的實體主機 IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ----------------------------------------------------------------
    # 2) 將 VNC/novnc 的 port 保持原樣
    ports:
      - "5903:5901"
      - "8082:8080"
    # ----------------------------------------------------------------
    # 3) 設定環境變數，指向 Host 端的 ROS Master (port 11311)
    #    以及讓 Host 能 callback 回這個容器的訂閱節點
    environment:
      - VNC_PASSWORD=ros000
      - ROS_MASTER_URI=http://host.docker.internal:11311
      # ROS_IP 可以簡單設定成容器自己的 bridge IP
      # 您也可以改為固定值，如 172.17.0.2，或在 entrypoint 動態計算
      - ROS_IP=host.docker.internal
    # ----------------------------------------------------------------
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  ROStest:
    external: true
